Fix the compiler error C2338 shown below that occurs when using Visual Studio Build Tools 2022 or later.
[build] D:\repos\opengl_course\projects\03_development_environment\cmake_project_example\build\install\include\spdlog\fmt\bundled\base.h(465,28): error C2338: static_assert failed: 'Unicode support requires compiling with /utf-8'